version: '3.7'
services:

  coupon-service:
    build:
      context: . 
      dockerfile: ./Dockerfile
    container_name: coupon-service
    restart: unless-stopped
    ports: 
      - ${COUPON_SERVICE_PORT:-8080}:${COUPON_SERVICE_PORT:-8080}
    environment:
      - COUPON_SERVICE_PORT=${COUPON_SERVICE_PORT:-8080}